### 🔐 Login with admin
POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "1@"
}

###
GET http://localhost:3000/matchposts
Accept: application/json

