export const profiles = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john.doe@example.com',
    avatar: 'https://i.pravatar.cc/150?u=1',
    phone: '123-456-7890',
    age: 28,
    position: 'Forward',
    bio: 'Passionate football player looking for a team.',
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    avatar: 'https://i.pravatar.cc/150?u=2',
    phone: '098-765-4321',
    age: 24,
    position: 'Midfielder',
    bio: 'Experienced midfielder with great passing skills.',
  },
  {
    id: 3,
    name: 'Peter Jones',
    email: 'peter.jones@example.com',
    avatar: 'https://i.pravatar.cc/150?u=3',
    phone: '555-555-5555',
    age: 31,
    position: 'Defender',
    bio: 'Solid defender, great at tackling.',
  },
  {
    id: 4,
    name: 'Mary Williams',
    email: 'mary.williams@example.com',
    avatar: 'https://i.pravatar.cc/150?u=4',
    phone: '111-222-3333',
    age: 29,
    position: 'Goalkeeper',
    bio: 'I save goals for a living.',
  },
];