export const mockData = [
        {
          postId: 1,
          teamId: 1,
          postedByPlayerId: 1,
          pitchId: 55,
          receivingTeamId: null,
          matchTime: '2025-07-03T18:00:00Z',
          description: 'Chúng tôi tìm đối thủ vào tối thứ 7',
          lookingFor: 'Opponent',
          postStatus: 'Open',
        },
        {
          postId: 2,
          teamId: 102,
          postedByPlayerId: 1002,
          pitchId: 56,
          receivingTeamId: 103,
          matchTime: '2025-07-05T20:00:00Z',
          description: 'Cần thêm đồng đội cho trận đấu 7 người',
          lookingFor: 'Teammate',
          postStatus: 'Open',
        },
        {
          postId: 3,
          teamId: 103,
          postedByPlayerId: 1003,
          pitchId: 57,
          receivingTeamId: 104,
          matchTime: '2025-07-10T19:30:00Z',
          description: 'Tìm đối thủ đá giao hữu vui vẻ',
          lookingFor: 'Opponent',
          postStatus: 'Open',
        },
        {
          postId: 4,
          teamId: 104,
          postedByPlayerId: 1004,
          pitchId: 58,
          receivingTeamId: null,
          matchTime: '2025-07-12T17:00:00Z',
          description: 'Tìm thêm đồng đội cho trận sân 7',
          lookingFor: 'Teammate',
          postStatus: 'Open',
        },
        {
          postId: 5,
          teamId: 105,
          postedByPlayerId: 1005,
          pitchId: 59,
          receivingTeamId: 106,
          matchTime: '2025-06-30T18:00:00Z',
          description: 'Trận đấu đã hoàn tất, cảm ơn anh em',
          lookingFor: 'Opponent',
          postStatus: 'Open',
        },
        {
          postId: 6,
          teamId: 106,
          postedByPlayerId: 1006,
          pitchId: 60,
          receivingTeamId: null,
          matchTime: '2025-07-07T20:00:00Z',
          description: 'Cần tìm đối thủ mạnh để đá cọ xát',
          lookingFor: 'Opponent',
          postStatus: 'Open',
        },
        {
          postId: 7,
          teamId: 107,
          postedByPlayerId: 1007,
          pitchId: 61,
          receivingTeamId: null,
          matchTime: '2025-07-09T18:30:00Z',
          description: 'Cần thêm 2 người chơi vị trí hậu vệ',
          lookingFor: 'Teammate',
          postStatus: 'Open',
        },
        {
          postId: 8,
          teamId: 108,
          postedByPlayerId: 1008,
          pitchId: 62,
          receivingTeamId: 109,
          matchTime: '2025-07-11T19:00:00Z',
          description: 'Giao hữu đội bạn đã xác nhận',
          lookingFor: 'Opponent',
          postStatus: 'Open',
        },
        {
          postId: 9,
          teamId: 109,
          postedByPlayerId: 1009,
          pitchId: 63,
          receivingTeamId: null,
          matchTime: '2025-07-14T21:00:00Z',
          description: 'Tìm đồng đội cùng thi đấu giải sắp tới',
          lookingFor: 'Teammate',
          postStatus: 'Open',
        },
        {
          postId: 10,
          teamId: 110,
          postedByPlayerId: 1010,
          pitchId: 64,
          receivingTeamId: null,
          matchTime: '2025-07-15T20:00:00Z',
          description: 'Đội mới thành lập cần tìm đối thủ để làm quen sân',
          lookingFor: 'Opponent',
          postStatus: 'Open',
        },
];
